name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies and prepare environment
        run: |
          $ErrorActionPreference = "Stop"
          if (Test-Path -Path "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\drive-desktop") {
            Remove-Item -Path "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\drive-desktop" -Recurse -Force
            Write-Host "Folder deleted"
          } else {
            Write-Host "Folder does not exist. Skipping deletion."
          }
          cd C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\
          git clone https://github.com/internxt/drive-desktop.git
          cd drive-desktop
          Copy-Item -Path "..\variables\.env" -Destination ".\"
          Copy-Item -Path "..\variables\.npmrc" -Destination ".\"
          yarn install

      - name: Run Python script
        run: |
          cd C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\
          python check-sign.py

      - name: Check release build files
        run: |
          cd "C:\Users\LENOVO\Desktop\Trabajo\drive-web-sign\drive-desktop"
          ls release/build/
